# -*- coding: utf-8 -*-
"""SupervisedML_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BFI_TZxq7hqqIK_2c60I2A2zZ-Y6ygKg
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, r2_score, mean_squared_error

df = pd.read_csv('/content/Netflix TV Shows and Movies.csv')

df.head()

df.info()

df.isnull().sum()

df.columns

df = df.drop(['age_certification'], axis = 1)

df = df.drop(['description'], axis = 1)

df['imdb_votes'] = df['imdb_votes'].fillna(df['imdb_votes'].median())

df.isnull().sum()

df.columns

df['type_encoded'] = df['type'].map({'MOVIE': 0, 'SHOW': 1})

features = ['type_encoded', 'runtime', 'votes_log', 'content_age', 'era', 'title_len']
X = df[features]
y = df['imdb_score']

X = pd.get_dummies(X)

X.head()

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, test_size=0.2)

df['votes_log'] = np.log1p(df['imdb_votes'])

df['title_len'] = df['title'].str.len()

df['imdb_votes'] = df['imdb_votes'].fillna(df['imdb_votes'].median())
df['votes_log'] = np.log1p(df['imdb_votes'])

df['content_age'] = 2024 - df['release_year']

bins = [0, 1980, 2000, 2010, 2020, 2030]
labels = [1, 2, 3, 4, 5]
df['era'] = pd.cut(df['release_year'], bins=bins, labels=labels).astype(int)

df['type_encoded'] = df['type'].map({'MOVIE': 0, 'SHOW': 1})

rf = RandomForestRegressor(random_state=42)

param_grid = {
    'n_estimators': [100, 200],
    'max_depth': [10, 20, None],
    'min_samples_leaf': [1, 2, 4]
}

grid_search = GridSearchCV(estimator=rf, param_grid=param_grid, cv=3, scoring='r2')
grid_search.fit(X_train, y_train)

best_model = grid_search.best_estimator_
# Check your new R2 score
print(f"New R2 Score: {best_model.score(X_test, y_test)}")

plt.scatter(y_test, y_pred, alpha=0.5)
plt.plot([y.min(), y.max()], [y.min(), y.max()], 'r--')
plt.title('Actual vs. Predicted IMDB Scores')
plt.savefig('actual_vs_predicted.png') # Save the plot
plt.show()

print(r2_score(y_test, y_pred))

print(mean_squared_error(y_test, y_pred))

plt.figure(figsize=(10, 5))
sns.histplot(df['imdb_score'], bins=20, kde=True)
plt.title('Distribution of IMDB Scores')
plt.xlabel('IMDB Score')
plt.ylabel('Frequency')
plt.show()

plt.figure(figsize=(8, 6))
sns.heatmap(df.select_dtypes(include=['number']).corr(), annot=True, cmap='coolwarm')
plt.title('Correlation Heatmap')
plt.savefig('correlation_heatmap.png') # Save the plot
plt.show()

sns.set(style="ticks")
pair_plot = sns.pairplot(df, hue='type', palette='Set1', diag_kind='kde')

# Adding a title
pair_plot.fig.suptitle('Pairplot of Features based on Content Type', y=1.02)

# 4. Save and Show
plt.savefig('netflix_pairplot.png')
plt.show()

from pptx import Presentation
from pptx.util import Inches

# Create a presentation object
prs = Presentation()

# Slide 1: Title Slide
slide_layout = prs.slide_layouts[0]
slide = prs.slides.add_slide(slide_layout)
slide.shapes.title.text = "Netflix ML Project Analysis"
slide.placeholders[1].text = "Linear Regression Results and Exploratory Data Analysis"

# List of charts we created earlier and actually saved
charts = [
    ("Actual vs Predicted IMDB Scores", "actual_vs_predicted.png"),
    ("Error Distribution", "error_distribution.png"),
    ("Correlation Heatmap", "correlation_heatmap.png"),
    ("Pairplot of Features based on Content Type", "netflix_pairplot.png")
]

# Add a slide for each chart
for title, file_path in charts:
    slide_layout = prs.slide_layouts[5] # Blank slide with title
    slide = prs.slides.add_slide(slide_layout)
    slide.shapes.title.text = title

    # Add image (left, top, width)
    slide.shapes.add_picture(file_path, Inches(1), Inches(1.5), width=Inches(8))

prs.save('Netflix_ML_Project.pptx')
print("PowerPoint created successfully!")

from IPython.display import IFrame, display

charts = [
    ("Actual vs Predicted IMDB Scores", "actual_vs_predicted.png"),
    ("Error Distribution", "error_distribution.png"),
    ("Correlation Heatmap", "correlation_heatmap.png"),
    ("Pairplot of Features based on Content Type", "netflix_pairplot.png")
]

for title, file_path in charts:
    print(f"\n--- {title} ---")
    display(IFrame(src=file_path, width=800, height=600))

!pip install python-pptx

!pip install sweetviz

# Uninstall potentially conflicting packages
!pip uninstall -y sweetviz scipy numpy

# Install compatible versions
!pip install numpy==2.0.0 --force-reinstall # Python 3.12 compatible numpy 2.x base
!pip install scipy==1.12.0 --force-reinstall # Scipy version compatible with numpy 2.0.0 and Python 3.12
!pip install sweetviz --force-reinstall # Reinstall sweetviz to pick up new dependencies

# Then run the sweetviz code
import sweetviz as sv
from IPython.display import IFrame
data = df
report = sv.analyze(data)
report.show_html('Netflix_EDA.html')
display(IFrame(src='Netflix_EDA.html', width=800, height=600))

!pip install ydata-profiling

from ydata_profiling import ProfileReport
from IPython.display import IFrame

# Generate the profile report
profile = ProfileReport(df, title="Netflix Dataset Profiling Report")

# Save the report to an HTML file
profile.to_file("Netflix_ydata_profiling_EDA.html")

# Display the report in the notebook
display(IFrame(src='Netflix_ydata_profiling_EDA.html', width=800, height=600))

!pip install numpy==1.23.5 --force-reinstall

import pickle

# Assuming 'best_model' is your trained RandomForestRegressor object
with open('netflix_model.pkl', 'wb') as file:
    pickle.dump(best_model, file)

print("Model saved as netflix_model.pkl")



"""# Task
The user wants to resolve the feature mismatch error encountered during model prediction. This involves ensuring the feature set (`X`) is correctly defined with the specified columns (`type_encoded`, `runtime`, `votes_log`, `content_age`, `era`, `title_len`), that the data is split consistently into training and testing sets, that the `RandomForestRegressor` model (`best_model`) is trained on these features, and finally, that predictions are made using this `best_model` on the corresponding `X_test` data.

Specifically, the `y_pred = model.predict(X_test)` call needs to be changed to `y_pred = best_model.predict(X_test)` to use the correctly trained model.

## Prepare Features and Target

### Subtask:
Define the feature set X using only the selected features from the df DataFrame (`type_encoded`, `runtime`, `votes_log`, `content_age`, `era`, `title_len`) and the target variable y as `imdb_score`. This ensures X contains only the intended columns.

**Reasoning**:
The subtask requires defining the feature set X and the target variable y using specific columns. I will create a list of the specified features and then assign X and y from the DataFrame df.
"""

features = ['type_encoded', 'runtime', 'votes_log', 'content_age', 'era', 'title_len']
X = df[features]
y = df['imdb_score']

print("Feature set X and target variable y defined successfully.")

"""**Reasoning**:
The subtask involves making predictions using the `best_model` on the test set. I will use the `predict` method of the `best_model` with `X_test` to generate `y_pred`.


"""

y_pred = best_model.predict(X_test)
print("Predictions made successfully using best_model.")

"""**Reasoning**:
With `y_pred` now available, the next logical step is to evaluate the model's performance using common regression metrics. I will calculate and print both the R2 score and the Mean Squared Error (MSE) to assess how well the model's predictions align with the actual values.


"""

print(f"R2 Score: {r2_score(y_test, y_pred)}")
print(f"Mean Squared Error: {mean_squared_error(y_test, y_pred)}")

"""## Split Data into Training and Test Sets

### Subtask:
Split the prepared `X` and `y` into training (`X_train`, `y_train`) and testing (`X_test`, `y_test`) sets using `train_test_split`. This ensures a consistent data split for model training and evaluation.

**Reasoning**:
I need to split the data into training and testing sets using `train_test_split` with the specified parameters (`test_size=0.2`, `random_state=42`) and then print the shapes of the resulting sets to verify the split.
"""

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"X_train shape: {X_train.shape}")
print(f"X_test shape: {X_test.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"y_test shape: {y_test.shape}")

"""## Train Random Forest Model

### Subtask:
Re-train the RandomForestRegressor model with hyperparameter tuning using GridSearchCV on the newly prepared X_train and y_train. This will create a best_model that is fitted on the correct and consistent set of features.

**Reasoning**:
The subtask requires retraining the RandomForestRegressor model with GridSearchCV. I will initialize the model, define the parameter grid (as it was already defined in the previous notebook state in cell `uCJypHvwOV77`), set up GridSearchCV, fit it to the training data, extract the best model, and then print its R2 score on the test set, as per the instructions.
"""

rf = RandomForestRegressor(random_state=42)

param_grid = {
    'n_estimators': [100, 200],
    'max_depth': [10, 20, None],
    'min_samples_leaf': [1, 2, 4]
}

grid_search = GridSearchCV(estimator=rf, param_grid=param_grid, cv=3, scoring='r2')
grid_search.fit(X_train, y_train)

best_model = grid_search.best_estimator_
print(f"New R2 Score: {best_model.score(X_test, y_test)}")

"""## Make Predictions

### Subtask:
Use the newly trained `best_model` to make predictions (`y_pred`) on the `X_test` data. This step should now work without feature mismatch errors.

**Reasoning**:
The subtask requires making predictions using the `best_model` on the `X_test` data. I will use the `predict` method to generate `y_pred`.
"""

y_pred = best_model.predict(X_test)
print("Predictions made successfully using best_model.")

"""## Final Task

### Subtask:
Confirm that the feature mismatch error is resolved and the prediction step executes successfully.

## Summary:

### Q&A
The feature mismatch error has been successfully resolved, and the prediction step executed without issues.

### Data Analysis Key Findings
*   The feature set `X` was successfully defined using the specified 6 columns: `type_encoded`, `runtime`, `votes_log`, `content_age`, `era`, and `title_len`, with `imdb_score` as the target variable `y`.
*   The data was consistently split into training and testing sets, allocating 4226 samples (80%) for training and 1057 samples (20%) for testing.
*   A `RandomForestRegressor` model was re-trained and hyperparameter-tuned using `GridSearchCV`, employing `n_estimators` (100, 200), `max_depth` (10, 20, None), and `min_samples_leaf` (1, 2, 4) as parameters.
*   The `best_model` successfully made predictions on the `X_test` data, confirming the resolution of the initial feature mismatch error.
*   The model achieved an R2 Score of approximately 0.243 on the test set, indicating that about 24.3% of the variance in `imdb_score` is explained by the features.
*   The Mean Squared Error (MSE) for the predictions was approximately 1.078.

### Insights or Next Steps
*   The current model's R2 score of 0.243 suggests that the selected features explain a relatively small portion of the variance in `imdb_score`. Further efforts in feature engineering, such as creating new features or exploring more relevant ones, could significantly improve model performance.
*   To potentially achieve higher predictive accuracy, consider exploring more advanced modeling techniques like Gradient Boosting Machines (e.g., XGBoost, LightGBM) or experimenting with different ensemble methods.
"""

plt.scatter(y_test, y_pred, alpha=0.5)
plt.plot([y.min(), y.max()], [y.min(), y.max()], 'r--')
plt.title('Actual vs. Predicted IMDB Scores')
plt.grid(True) # Save the plot
plt.show()

plt.hist(y_test - y_pred, bins=20, alpha=0.5)
plt.title('Error Distribution')
plt.xlabel('Residuals')
plt.ylabel('Frequency')
plt.grid(True)
plt.savefig('error_distribution.png') # Save the plot
plt.show()

plt.pie(df['type'].value_counts(), labels=df['type'].unique(), autopct='%1.1f%%')
plt.title('Distribution of Content Types')
#plt.savefig('content_type_distribution.png') # Save the plot
plt.xlabel('Content Type')
plt.ylabel('Percentage')
plt.show()

